### ISSUE TITLE
I have some error in CuBe as show in attached file.

### ISSUE THREAD

**Issue by sarunyooc** [tggwlcube/CuBe_SCSC#6]
![issue1](https://cloud.githubusercontent.com/assets/9924429/6745851/21ce914c-cef0-11e4-80bb-3db6171fb533.png)

**Comment by sarunyooc** [comment]
Date Time Stamp : 2015-03-20 13:58:38
Source of error :    at System.Data.OleDb.OleDbDataReader.ProcessResults(OleDbHResult hr)
   at System.Data.OleDb.OleDbDataReader.NextResult()
   at System.Data.OleDb.OleDbCommand.ExecuteReaderInternal(CommandBehavior behavior, String method)
   at System.Data.OleDb.OleDbCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.OleDb.OleDbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet)
   at CuBe.OrderDetail.PopulateData(String v_strOrder)
Error Details : Conversion failed when converting date and/or time from character string.

---

**Comment by hemantbansal** [comment]
Hi Khun Sarunyoo, Can i have Teamviewer 8 password in your laptop.
Many times it happend , that whenever u are available , i am not available, and when i am available, your are not free. So can we fix up some time when we both are free. so that i  can see this issue in your laptop.

**Comment by hemantbansal** [comment]
It was a date format problem, Team viewer is taken, and date  format is changed from Thai to English
